version: '2'
services:  
  docker-jenkins:
    container_name: test_container2
    build:
      context: .
    image: docker-jenkins/tag1
    volumes:
      - /var/lib/jenkins/workspace/jenkins-docker-integration:/var/lib/jenkins/workspace/jenkins-docker-integration