version: '2'
services:  
  docker-jenkins:
    container_name: test_container
    build:
      context: .
    image: docker-jenkins:tag1
    volumes:
      - /var/lib/jenkins/workspace/test:/var/lib/jenkins/workspace/test